### ISSUE TITLE
Provide custom codes for storing data directly into mongo without JsonObject

### ISSUE THREAD

**Issue by halajos** [Deutsche-Boerse-Risk/DAVe-StoreManager#19]
While storing and fetching data to/from mongo database through intermediary JsonObject gives flexibility
and general purpose usage, it is not necessarily very efficient. With custom provided codecs we could save considerable amount of CPU and memory. Another benefit is that data stored/fetched from the database will be strong typed.

**Comment by halajos** [comment]
Performance tests (loaded 7 snapshots followed by 30x requests on the position report of the biggest clearer)
Before:
![image](https://cloud.githubusercontent.com/assets/25768824/26627778/e0da7248-45fb-11e7-9562-cd8377ca8d41.png)

After:
![image](https://cloud.githubusercontent.com/assets/25768824/26627837/106b45c8-45fc-11e7-8e89-a48be3ca8a67.png)

**Comment by zerola** [comment]
Implemented.
